# @saas-ui-pro/* packages are private and require you to login to the private registry.
# @see https://saas-ui.dev/docs/pro/installation/yarn
npmScopes:
  saas-ui-pro:
    npmRegistryServer: 'https://npm.saas-ui.dev'

# Uncomment the following if you want log in using env variables, eg for CI/CD pipelines.
# npmRegistries:
#   //npm.saas-ui.dev:
#     npmAuthIdent: '${SAAS_UI_TOKEN:-}'
#     npmAlwaysAuth: true

enableGlobalCache: true

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.5.0.cjs